version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80' # nginx listen on 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - frontend
      - backend

  frontend:
    container_name: 'client'
    restart: 'always'
    image: shinhyeok/dobda-client:latest
    ports:
      - '3000:3000'
    networks:
      - front-back

  backend:
    container_name: 'server'
    restart: 'always'
    image: shinhyeok/dobda-server:latest
    ports:
      - '8080:8080'
    networks:
      - front-back

networks:
  front-back:
    driver: bridge
