name: Build & Publish

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: [main]
  workflow_dispatch: # Manually run the workflow

jobs:
  next-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: create env file
        run: echo "${{ secrets.ENV_VARS }}" >> .env
      #         run: |
      #           jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
      #         env:
      #           SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Images

        uses: docker/build-push-action@v3
        with:
          #           run: echo "${{ secrets.ENV_VARS }}" >> .env #success code
          dockerfile: .Dockerfile
          context: .
          push: false
          tags: shinhyeok/dobda-client:latest
